controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_controller/JointStateController

    rrbot_controller:
      type: rrbot_controller/RRBotController

rrbot_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position
